services:
  - type: web
    name: garageguru-production
    env: node
    plan: starter
    buildCommand: npm ci --include=dev && npm run build && mkdir -p public && cp -r dist/public/* public/  
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: PORT  
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: garageguru-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: SUPER_ADMIN_EMAIL
        sync: false
    healthCheckPath: /health
    
databases:
  - name: garageguru-db
    databaseName: garageguru
    user: admin
    plan: starter