[build]
  publish = "."
  command = "echo 'ServiceGuru Keep-Alive Service Ready'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=3600"

[[redirects]]
  from = "/ping"
  to = "https://garageguru-whh7.onrender.com"
  status = 302
  force = true

[[redirects]]
  from = "/health"
  to = "/index.html"
  status = 200